coala/gh-board

.travis.yml, script/build.sh
Netlify does not like invoking multiple commands.
=> build.sh: New script to share build logic

src/components/app/filter-dropdown.jsx, src/components/by-milestone-view.jsx, src/components/repo-kanban.jsx
Related to https://github.com/coala/gh-board/issues/30
=> Remove TODOs in components code

src/components/app/nav.jsx
Fixes https://github.com/coala/gh-board/issues/40
=> nav.jsx: Fix broken link on header

package-lock.json, package.json, script/fetch-issues.js, script/queries/github_pr_info.graphql, script/queries/github_reaction_info.graphql, script/queries/index.js, src/initial-data.js
Closes https://github.com/coala/gh-board/issues/38
=> Pre-fetch pull request review comments & reactions

package.json, test/index.js
Run ESLint on script & test directory and fix ESLint warnings.
Closes https://github.com/coala/gh-board/issues/24
=> package.json: Add linting on script & test

README.md
=> README.md: Remove Easter egg section

.gitignore, package-lock.json, package.json, script/run-test.sh, test/index.js
Use selenium-standalone instead of webdriver-manager.
Fixes https://github.com/coala/gh-board/issues/60
=> Fix Travis failure

.gitignore
Fixes https://github.com/coala/gh-board/issues/68
=> Sync gitignore

.travis.yml
Closes https://github.com/coala/gh-board/issues/52
=> .travis.yml: Enable keep-history

.travis.yml, script/run-test.sh
Verify `issues.json` and `recent-issues.json`
files exist after build.
Closes https://github.com/coala/gh-board/issues/74
=> run-test.sh: Verify files exist

src/components/reactions.jsx, src/components/repo-kanban.jsx, src/components/review-blurb.jsx, src/components/review-list.jsx, src/components/review.jsx, src/filter-store.js, style/issue-list.less, style/review.less
Create a new column, namely `meta-review in need`,
which displays reviews that in need of meta-reviews.
Closes #64
=> Setup meta review in need

script/queries/export.js, script/queries/github_issue_info.js, script/queries/github_label_info.js, script/queries/github_pr_info.js, script/queries/github_reaction_info.js, src/github-client.js, src/github-graphql.js, src/issue-store.js
Related to https://github.com/coala/gh-board/issues/26
=> Setup GraphQL client

src/router.jsx
Fixes https://github.com/coala/gh-board/issues/134
=> Fix /dashboard routing

src/components/app/filter-dropdown.jsx, src/components/repo-kanban.jsx, src/filter-store.js, src/github-client.js, src/route-utils.js
=> Add review filters functionality

src/components/app/nav.jsx, src/components/etherpad-modal.jsx, src/components/etherpad.jsx
=> Hiroshis' Etherpad

netlify.toml, script/run-test.sh, script/verify-files.sh
Closes https://github.com/coala/gh-board/issues/140
=> Netlify build: Verify pre-fetched files exist

src/components/reactions.jsx, src/components/review-blurb.jsx, style/review.less, test/src/components/__snapshots__/reactions.test.js.snap
Related to https://github.com/coala/gh-board/issues/84
=> Enhance meta-review UI

script/fetch-issues.js, src/github-client.js
Add Travisbuddy as an ignore author,
fix ack & unack in ignore content.
Fixes https://github.com/coala/gh-board/issues/149
=> Fix review fetch ignore settings

script/queries/github_reaction_add.graphql, script/queries/github_reaction_remove.graphql, script/queries/index.js, src/components/dashboard.jsx, src/components/login-auth.jsx, src/components/reactions.jsx, src/components/repo-kanban.jsx, src/components/review.jsx, src/github-graphql.js, style/review.less, test/src/components/__snapshots__/reactions.test.js.snap, test/src/components/reactions.test.js
Users can do meta-reviews directly on the gh-board.
Closes https://github.com/coala/gh-board/issues/146
=> Add reaction mutation functionality

README.md
Closes https://github.com/coala/gh-board/issues/152
=> README.md: Add meta-review section

package.json
package.json: Convert tab to spaces
Closes https://github.com/coala/gh-board/issues/148
=> package.json: Convert tab to spaces

src/router.jsx
src/router.jsx: replaced browserHistory with history
Closes #163
=> src/router.jsx: Change browserHistory to history

src/github-graphql.js
Makes console message shorter. Thus makes it easier to spot real problems.
Closes https://github.com/coala/gh-board/issues/88
=> github-graphql.js: Change console message.

src/components/app/nav.jsx
Remove the menu item for starring the repository.
Closes https://github.com/coala/gh-board/issues/90
=> nav.jsx: Remove menu to star repo

src/components/issue.jsx
=> issue.jsx: Add link to PR /files tab
